#!/bin/bash


for tpl in $(find /etc -type f -name '*.tpl.*'); do
  envsubst < "$tpl" > "$(echo "$tpl" | sed 's/.tpl//')"
done


ln -sf /etc/sv/socklog-unix /var/service/
ln -sf /etc/sv/cronie /var/service/
ln -sf /etc/sv/tailscaled /var/service/
ln -sf /etc/sv/svagent /var/service/

sv start tailscaled || exit 1

export TS_HOSTNAME=${TS_HOSTNAME:-${HOSTNAEM}}
/bin/tailscale up \
  --ssh \
  --accept-routes \
  --auth-key "${TSKEY}" \
  --hostname "$TS_HOSTNAME" || exit 1

FQDN="$(tailscale status --json 2>/dev/null | jq .Self.DNSName | tr -d '\"' | sed 's/net./net/')"

cd /tmp && tailscale cert "${FQDN}"


/bin/sleep infinity